version: '3.9'

services:
  django_gunicorn:
    build: ./pc_configurator
    volumes:
      - ./pc_configurator:/usr/src/app/
      - static_data:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./pc_configurator/.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=das
      - POSTGRES_PASSWORD=Hello123
      - POSTGRES_DB=pc_conf
  nginx:
    build: ./pc_configurator/nginx
    depends_on:
      - django_gunicorn
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
    
volumes:
  postgres_data:
  static_data: